repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict

      - id: check-merge-conflict

      - id: check-yaml

      - id: check-toml

      # Make sure not break significant newlines in markdown
      # files, or yaml action files.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.(yaml|yml)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        name: checking for spelling issues
